server:
  port: 8011

spring:
  application:
    name: wengxs-mq-consumer

  # springboot整合rabbitmq基本配置
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    # 消费端配置
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
