server:
  port: 8002

spring:
  application:
    name: wengxs-upms
  profiles:
    active: dev
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: wengxs-config
#      name: ${spring.application.name}
#      profile: ${spring.profiles.active}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wengxs_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
#  jackson:
#    date-format: "yyyy-MM-dd HH:mm:ss"
#    time-zone: GMT+8
#    locale: zh_CN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  type-aliases-package: com.wengxs.cloud.model
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: simple
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl