server:
  port: 8761

spring:
  application:
    name: wengxs-eureka
#  security:
#    user:
#      name: wengxs
#      password: wengxs

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
